// <auto-generated />
using System;
using Grind.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Grind.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260914183923_AntrenmanHareketListesi")]
    partial class AntrenmanHareketListesi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Grind.Api.Models.Entities.AiInsight", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("EstimatedCostUsd")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly?>("RangeFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("RangeTo")
                        .HasColumnType("date");

                    b.Property<long?>("SetEntryId")
                        .HasColumnType("bigint");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("WorkoutSessionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SetEntryId");

                    b.HasIndex("WorkoutSessionId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("AiInsights");
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.BodyWeightLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Weight")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RecordedAt");

                    b.ToTable("BodyWeightLogs", t =>
                        {
                            t.HasCheckConstraint("CK_BodyWeightLog_Weight_Positive", "\"Weight\" > 0");
                        });
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.Exercise", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<long>("Id"), 1000L, null, null, null, null, null);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("UserId", "Name"), false);

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Bench Press"
                        },
                        new
                        {
                            Id = 2L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Incline Dumbbell Press"
                        },
                        new
                        {
                            Id = 3L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Overhead Press"
                        },
                        new
                        {
                            Id = 4L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Dips"
                        },
                        new
                        {
                            Id = 5L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Triceps Pushdown"
                        },
                        new
                        {
                            Id = 6L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Pull-up"
                        },
                        new
                        {
                            Id = 7L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Barbell Row"
                        },
                        new
                        {
                            Id = 8L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Lat Pulldown"
                        },
                        new
                        {
                            Id = 9L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Barbell Curl"
                        },
                        new
                        {
                            Id = 10L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Face Pull"
                        },
                        new
                        {
                            Id = 11L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Squat"
                        },
                        new
                        {
                            Id = 12L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Deadlift"
                        },
                        new
                        {
                            Id = 13L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Romanian Deadlift"
                        },
                        new
                        {
                            Id = 14L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Leg Press"
                        },
                        new
                        {
                            Id = 15L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Leg Curl"
                        });
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.ExerciseMedia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExerciseId")
                        .HasColumnType("bigint");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("ExerciseMedia");
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.SessionExercise", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ExerciseId")
                        .HasColumnType("bigint");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int?>("PlannedSets")
                        .HasColumnType("integer");

                    b.Property<int>("RestSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(90);

                    b.Property<long>("WorkoutSessionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutSessionId", "ExerciseId")
                        .IsUnique();

                    b.ToTable("SessionExercises", t =>
                        {
                            t.HasCheckConstraint("CK_SessionExercise_PlannedSets_Positive", "\"PlannedSets\" IS NULL OR \"PlannedSets\" > 0");

                            t.HasCheckConstraint("CK_SessionExercise_RestSeconds_Range", "\"RestSeconds\" >= 0 AND \"RestSeconds\" <= 900");
                        });
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.SetEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExerciseId")
                        .HasColumnType("bigint");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<int?>("Rir")
                        .HasColumnType("integer");

                    b.Property<decimal>("Weight")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<long>("WorkoutSessionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutSessionId");

                    b.HasIndex("ExerciseId", "WorkoutSessionId");

                    b.ToTable("SetEntries", t =>
                        {
                            t.HasCheckConstraint("CK_SetEntry_Reps_Positive", "\"Reps\" > 0");

                            t.HasCheckConstraint("CK_SetEntry_Rir_NonNegative", "\"Rir\" IS NULL OR \"Rir\" >= 0");

                            t.HasCheckConstraint("CK_SetEntry_Weight_NonNegative", "\"Weight\" >= 0");
                        });
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.TemplateExercise", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ExerciseId")
                        .HasColumnType("bigint");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("PlannedSets")
                        .HasColumnType("integer");

                    b.Property<int>("RestSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(90);

                    b.Property<long>("WorkoutTemplateId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutTemplateId", "OrderIndex");

                    b.ToTable("TemplateExercises", t =>
                        {
                            t.HasCheckConstraint("CK_TemplateExercise_PlannedSets_Positive", "\"PlannedSets\" > 0");

                            t.HasCheckConstraint("CK_TemplateExercise_RestSeconds_Range", "\"RestSeconds\" >= 0 AND \"RestSeconds\" <= 900");
                        });
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.WorkoutSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("TemplateId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.HasIndex("UserId", "StartedAt");

                    b.ToTable("WorkoutSessions", t =>
                        {
                            t.HasCheckConstraint("CK_WorkoutSession_EndedAt_After_StartedAt", "\"EndedAt\" IS NULL OR \"EndedAt\" > \"StartedAt\"");
                        });
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.WorkoutTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("WorkoutTemplates");
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.AiInsight", b =>
                {
                    b.HasOne("Grind.Api.Models.Entities.SetEntry", "SetEntry")
                        .WithMany("AiInsights")
                        .HasForeignKey("SetEntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Grind.Api.Models.Entities.User", "User")
                        .WithMany("AiInsights")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grind.Api.Models.Entities.WorkoutSession", "WorkoutSession")
                        .WithMany("AiInsights")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SetEntry");

                    b.Navigation("User");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.BodyWeightLog", b =>
                {
                    b.HasOne("Grind.Api.Models.Entities.User", "User")
                        .WithMany("BodyWeightLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.Exercise", b =>
                {
                    b.HasOne("Grind.Api.Models.Entities.User", "User")
                        .WithMany("Exercises")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.ExerciseMedia", b =>
                {
                    b.HasOne("Grind.Api.Models.Entities.Exercise", "Exercise")
                        .WithMany("Media")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.SessionExercise", b =>
                {
                    b.HasOne("Grind.Api.Models.Entities.Exercise", "Exercise")
                        .WithMany("SessionExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grind.Api.Models.Entities.WorkoutSession", "WorkoutSession")
                        .WithMany("SessionExercises")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.SetEntry", b =>
                {
                    b.HasOne("Grind.Api.Models.Entities.Exercise", "Exercise")
                        .WithMany("SetEntries")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grind.Api.Models.Entities.WorkoutSession", "WorkoutSession")
                        .WithMany("SetEntries")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.TemplateExercise", b =>
                {
                    b.HasOne("Grind.Api.Models.Entities.Exercise", "Exercise")
                        .WithMany("TemplateExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grind.Api.Models.Entities.WorkoutTemplate", "WorkoutTemplate")
                        .WithMany("TemplateExercises")
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.WorkoutSession", b =>
                {
                    b.HasOne("Grind.Api.Models.Entities.WorkoutTemplate", "Template")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Grind.Api.Models.Entities.User", "User")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Template");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.WorkoutTemplate", b =>
                {
                    b.HasOne("Grind.Api.Models.Entities.User", "User")
                        .WithMany("WorkoutTemplates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.Exercise", b =>
                {
                    b.Navigation("Media");

                    b.Navigation("SessionExercises");

                    b.Navigation("SetEntries");

                    b.Navigation("TemplateExercises");
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.SetEntry", b =>
                {
                    b.Navigation("AiInsights");
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.User", b =>
                {
                    b.Navigation("AiInsights");

                    b.Navigation("BodyWeightLogs");

                    b.Navigation("Exercises");

                    b.Navigation("WorkoutSessions");

                    b.Navigation("WorkoutTemplates");
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.WorkoutSession", b =>
                {
                    b.Navigation("AiInsights");

                    b.Navigation("SessionExercises");

                    b.Navigation("SetEntries");
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.WorkoutTemplate", b =>
                {
                    b.Navigation("TemplateExercises");

                    b.Navigation("WorkoutSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
