// <auto-generated />
using System;
using Grind.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Grind.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260921145119_AddChestSupportedMachineRows")]
    partial class AddChestSupportedMachineRows
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Grind.Api.Models.Entities.AiInsight", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("EstimatedCostUsd")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly?>("RangeFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("RangeTo")
                        .HasColumnType("date");

                    b.Property<long?>("SetEntryId")
                        .HasColumnType("bigint");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("WorkoutSessionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SetEntryId");

                    b.HasIndex("WorkoutSessionId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("AiInsights");
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.BodyWeightLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("BodyFatPercent")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal?>("HeightCm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal?>("HipCm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("WaistCm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RecordedAt");

                    b.ToTable("BodyWeightLogs", t =>
                        {
                            t.HasCheckConstraint("CK_BodyWeightLog_BodyFatPercent_Positive", "\"BodyFatPercent\" > 0");

                            t.HasCheckConstraint("CK_BodyWeightLog_HeightCm_Positive", "\"HeightCm\" > 0");

                            t.HasCheckConstraint("CK_BodyWeightLog_HipCm_Positive", "\"HipCm\" > 0");

                            t.HasCheckConstraint("CK_BodyWeightLog_WaistCm_Positive", "\"WaistCm\" > 0");

                            t.HasCheckConstraint("CK_BodyWeightLog_Weight_Positive", "\"Weight\" > 0");
                        });
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.Exercise", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<long>("Id"), 1000L, null, null, null, null, null);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("UserId", "Name"), false);

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Bench Press"
                        },
                        new
                        {
                            Id = 2L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Incline Dumbbell Press"
                        },
                        new
                        {
                            Id = 3L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Overhead Press"
                        },
                        new
                        {
                            Id = 4L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Dips"
                        },
                        new
                        {
                            Id = 5L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Triceps Pushdown"
                        },
                        new
                        {
                            Id = 6L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Pull-up"
                        },
                        new
                        {
                            Id = 7L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Barbell Row"
                        },
                        new
                        {
                            Id = 8L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Lat Pulldown"
                        },
                        new
                        {
                            Id = 9L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Barbell Curl"
                        },
                        new
                        {
                            Id = 10L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Face Pull"
                        },
                        new
                        {
                            Id = 11L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Squat"
                        },
                        new
                        {
                            Id = 12L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Deadlift"
                        },
                        new
                        {
                            Id = 13L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Romanian Deadlift"
                        },
                        new
                        {
                            Id = 14L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Leg Press"
                        },
                        new
                        {
                            Id = 15L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Leg Curl"
                        },
                        new
                        {
                            Id = 16L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "45 Back Focused Extension"
                        },
                        new
                        {
                            Id = 17L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "45 Dumbbell Back Focused Extension"
                        },
                        new
                        {
                            Id = 18L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "45 Dumbbell Glute Focused Extension"
                        },
                        new
                        {
                            Id = 19L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "45 Dumbbell Single Leg Glute Focused Extension"
                        },
                        new
                        {
                            Id = 20L,
                            Category = "Other",
                            IsArchived = false,
                            Name = "Ab Rollout"
                        },
                        new
                        {
                            Id = 21L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Air Box Squat"
                        },
                        new
                        {
                            Id = 22L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Air Squat"
                        },
                        new
                        {
                            Id = 23L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Alternating Dumbbell Curl"
                        },
                        new
                        {
                            Id = 24L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Banded Push Up"
                        },
                        new
                        {
                            Id = 25L,
                            Category = "Other",
                            IsArchived = false,
                            Name = "Barbell Ab Rollout"
                        },
                        new
                        {
                            Id = 26L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Barbell Box Squat"
                        },
                        new
                        {
                            Id = 27L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Barbell Floor Press"
                        },
                        new
                        {
                            Id = 28L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Barbell Front Squat"
                        },
                        new
                        {
                            Id = 29L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Barbell Glute Bridge"
                        },
                        new
                        {
                            Id = 30L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Barbell Good Morning"
                        },
                        new
                        {
                            Id = 31L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Barbell Hip Thrust"
                        },
                        new
                        {
                            Id = 32L,
                            Category = "Other",
                            IsArchived = false,
                            Name = "Barbell Hold"
                        },
                        new
                        {
                            Id = 33L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Barbell Overhead Press"
                        },
                        new
                        {
                            Id = 34L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Barbell Overhead Squat"
                        },
                        new
                        {
                            Id = 35L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Cable Front Raise"
                        },
                        new
                        {
                            Id = 36L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Cable Glute Pullthrough"
                        },
                        new
                        {
                            Id = 37L,
                            Category = "Other",
                            IsArchived = false,
                            Name = "Cable High to Low Chop"
                        },
                        new
                        {
                            Id = 38L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Cable Hip Abduction"
                        },
                        new
                        {
                            Id = 39L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Cable Hip Adduction"
                        },
                        new
                        {
                            Id = 40L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Cable Kickback"
                        },
                        new
                        {
                            Id = 41L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Cable Lateral Raise"
                        },
                        new
                        {
                            Id = 42L,
                            Category = "Other",
                            IsArchived = false,
                            Name = "Cable Low to High Chop"
                        },
                        new
                        {
                            Id = 43L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Cable Overhead Extension"
                        },
                        new
                        {
                            Id = 44L,
                            Category = "Other",
                            IsArchived = false,
                            Name = "Cable Pallof Hold"
                        },
                        new
                        {
                            Id = 45L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Machine Assisted Dips"
                        },
                        new
                        {
                            Id = 46L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Machine Assisted Pull Up"
                        },
                        new
                        {
                            Id = 47L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Machine Back Extension"
                        },
                        new
                        {
                            Id = 48L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Machine Glute Kickback"
                        },
                        new
                        {
                            Id = 49L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Machine Lateral Raise"
                        },
                        new
                        {
                            Id = 50L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Machine Overhead Press"
                        },
                        new
                        {
                            Id = 51L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Machine Pulldown"
                        },
                        new
                        {
                            Id = 52L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Machine Seated Hip Abduction"
                        },
                        new
                        {
                            Id = 53L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Machine Seated Hip Adduction"
                        },
                        new
                        {
                            Id = 54L,
                            Category = "Other",
                            IsArchived = false,
                            Name = "Med Ball Rotational Throw"
                        },
                        new
                        {
                            Id = 55L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Miniband Hip Abduction"
                        },
                        new
                        {
                            Id = 56L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Seated Cable Face Pull"
                        },
                        new
                        {
                            Id = 57L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Seated Cable Row"
                        },
                        new
                        {
                            Id = 58L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Seated Calf Raise"
                        },
                        new
                        {
                            Id = 59L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Seated Dumbbell Shoulder Press"
                        },
                        new
                        {
                            Id = 60L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Seated Leg Curl"
                        },
                        new
                        {
                            Id = 61L,
                            Category = "Other",
                            IsArchived = false,
                            Name = "Side Plank"
                        },
                        new
                        {
                            Id = 62L,
                            Category = "Other",
                            IsArchived = false,
                            Name = "Side Plank Rotation"
                        },
                        new
                        {
                            Id = 63L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Single Arm Banded OHP"
                        },
                        new
                        {
                            Id = 64L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Single Arm Banded Row"
                        },
                        new
                        {
                            Id = 65L,
                            Category = "Other",
                            IsArchived = false,
                            Name = "Single Arm Barbell Hold"
                        },
                        new
                        {
                            Id = 66L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Incline Barbell Bench Press"
                        },
                        new
                        {
                            Id = 67L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Decline Barbell Bench Press"
                        },
                        new
                        {
                            Id = 68L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Flat Dumbbell Bench Press"
                        },
                        new
                        {
                            Id = 69L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Decline Dumbbell Bench Press"
                        },
                        new
                        {
                            Id = 70L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Neutral Grip Dumbbell Press"
                        },
                        new
                        {
                            Id = 71L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Flat Smith Machine Press"
                        },
                        new
                        {
                            Id = 72L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Incline Smith Machine Press"
                        },
                        new
                        {
                            Id = 73L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Decline Smith Machine Press"
                        },
                        new
                        {
                            Id = 74L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Machine Chest Press"
                        },
                        new
                        {
                            Id = 75L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Incline Machine Chest Press"
                        },
                        new
                        {
                            Id = 76L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Converging Chest Press"
                        },
                        new
                        {
                            Id = 77L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Flat Dumbbell Fly"
                        },
                        new
                        {
                            Id = 78L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Incline Dumbbell Fly"
                        },
                        new
                        {
                            Id = 79L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Decline Dumbbell Fly"
                        },
                        new
                        {
                            Id = 80L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "High-to-Low Cable Fly"
                        },
                        new
                        {
                            Id = 81L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Mid-Pulley Cable Fly"
                        },
                        new
                        {
                            Id = 82L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Low-to-High Cable Fly"
                        },
                        new
                        {
                            Id = 83L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Pec Deck"
                        },
                        new
                        {
                            Id = 84L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Push-up"
                        },
                        new
                        {
                            Id = 85L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Incline Push-up"
                        },
                        new
                        {
                            Id = 86L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Decline Push-up"
                        },
                        new
                        {
                            Id = 87L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Deficit Push-up"
                        },
                        new
                        {
                            Id = 88L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Close-Grip Lat Pulldown"
                        },
                        new
                        {
                            Id = 89L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Reverse Grip Lat Pulldown"
                        },
                        new
                        {
                            Id = 90L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Single-Arm Cable Lat Pulldown"
                        },
                        new
                        {
                            Id = 91L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Chin-up"
                        },
                        new
                        {
                            Id = 92L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Neutral Grip Pull-up"
                        },
                        new
                        {
                            Id = 93L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Yates Row"
                        },
                        new
                        {
                            Id = 94L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Pendlay Row"
                        },
                        new
                        {
                            Id = 95L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Single-Arm Dumbbell Row"
                        },
                        new
                        {
                            Id = 96L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Chest-Supported Incline Dumbbell Row"
                        },
                        new
                        {
                            Id = 97L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Wide-Grip Seated Cable Row"
                        },
                        new
                        {
                            Id = 98L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Single-Arm Seated Cable Row"
                        },
                        new
                        {
                            Id = 99L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "T-Bar Row"
                        },
                        new
                        {
                            Id = 100L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Iso-Lateral Machine Row"
                        },
                        new
                        {
                            Id = 101L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Trap Bar Deadlift"
                        },
                        new
                        {
                            Id = 102L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Rack Pull"
                        },
                        new
                        {
                            Id = 103L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Straight-Arm Cable Pulldown"
                        },
                        new
                        {
                            Id = 104L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Seated Barbell Overhead Press"
                        },
                        new
                        {
                            Id = 105L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Behind-the-Neck Press"
                        },
                        new
                        {
                            Id = 106L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Standing Dumbbell Shoulder Press"
                        },
                        new
                        {
                            Id = 107L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Arnold Press"
                        },
                        new
                        {
                            Id = 108L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Seated Smith Machine Overhead Press"
                        },
                        new
                        {
                            Id = 109L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Plate-Loaded Shoulder Press Machine"
                        },
                        new
                        {
                            Id = 110L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Pin-Loaded Shoulder Press Machine"
                        },
                        new
                        {
                            Id = 111L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Standing Dumbbell Lateral Raise"
                        },
                        new
                        {
                            Id = 112L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Seated Dumbbell Lateral Raise"
                        },
                        new
                        {
                            Id = 113L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Incline Lean-Away Lateral Raise"
                        },
                        new
                        {
                            Id = 114L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Cuff Cable Lateral Raise"
                        },
                        new
                        {
                            Id = 115L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Reverse Pec Deck"
                        },
                        new
                        {
                            Id = 116L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Chest-Supported Incline Dumbbell Rear Delt Fly"
                        },
                        new
                        {
                            Id = 117L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Bent-over Dumbbell Rear Delt Raise"
                        },
                        new
                        {
                            Id = 118L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Cable Rear Delt Crossover"
                        },
                        new
                        {
                            Id = 119L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Barbell Front Raise"
                        },
                        new
                        {
                            Id = 120L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Dumbbell Front Raise"
                        },
                        new
                        {
                            Id = 121L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Low-Bar Back Squat"
                        },
                        new
                        {
                            Id = 122L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Zercher Squat"
                        },
                        new
                        {
                            Id = 123L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Hack Squat"
                        },
                        new
                        {
                            Id = 124L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Pendulum Squat"
                        },
                        new
                        {
                            Id = 125L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Smith Machine Squat"
                        },
                        new
                        {
                            Id = 126L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Bulgarian Split Squat"
                        },
                        new
                        {
                            Id = 127L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Walking Lunge"
                        },
                        new
                        {
                            Id = 128L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Reverse Lunge"
                        },
                        new
                        {
                            Id = 129L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Dumbbell Step-Up"
                        },
                        new
                        {
                            Id = 130L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Seated Leg Extension"
                        },
                        new
                        {
                            Id = 131L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Sissy Squat"
                        },
                        new
                        {
                            Id = 132L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Smith Machine Hip Thrust"
                        },
                        new
                        {
                            Id = 133L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Glute Drive Machine"
                        },
                        new
                        {
                            Id = 134L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Single-Leg Hip Thrust"
                        },
                        new
                        {
                            Id = 135L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Dumbbell Romanian Deadlift"
                        },
                        new
                        {
                            Id = 136L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "B-Stance Romanian Deadlift"
                        },
                        new
                        {
                            Id = 137L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Standing Single-Leg Curl"
                        },
                        new
                        {
                            Id = 138L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Standing Calf Raise"
                        },
                        new
                        {
                            Id = 139L,
                            Category = "Legs",
                            IsArchived = false,
                            Name = "Leg Press Calf Raise"
                        },
                        new
                        {
                            Id = 140L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "EZ-Bar Preacher Curl"
                        },
                        new
                        {
                            Id = 141L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Single-Arm Dumbbell Preacher Curl"
                        },
                        new
                        {
                            Id = 142L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Machine Preacher Curl"
                        },
                        new
                        {
                            Id = 143L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Incline Dumbbell Curl"
                        },
                        new
                        {
                            Id = 144L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Concentration Curl"
                        },
                        new
                        {
                            Id = 145L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Spider Curl"
                        },
                        new
                        {
                            Id = 146L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Standing Dumbbell Hammer Curl"
                        },
                        new
                        {
                            Id = 147L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Seated Dumbbell Hammer Curl"
                        },
                        new
                        {
                            Id = 148L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Cable Rope Hammer Curl"
                        },
                        new
                        {
                            Id = 149L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Reverse Grip Barbell Curl"
                        },
                        new
                        {
                            Id = 150L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Low Pulley Cable Curl"
                        },
                        new
                        {
                            Id = 151L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "High Cable Curl"
                        },
                        new
                        {
                            Id = 152L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Cable Rope Pushdown"
                        },
                        new
                        {
                            Id = 153L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Reverse Grip Cable Pushdown"
                        },
                        new
                        {
                            Id = 154L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Skull Crusher"
                        },
                        new
                        {
                            Id = 155L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Incline Skull Crusher"
                        },
                        new
                        {
                            Id = 156L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Decline Skull Crusher"
                        },
                        new
                        {
                            Id = 157L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Overhead Dumbbell Triceps Extension"
                        },
                        new
                        {
                            Id = 158L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Close-Grip Bench Press"
                        },
                        new
                        {
                            Id = 159L,
                            Category = "Push",
                            IsArchived = false,
                            Name = "Bench Dips"
                        },
                        new
                        {
                            Id = 160L,
                            Category = "Other",
                            IsArchived = false,
                            Name = "Crunch"
                        },
                        new
                        {
                            Id = 161L,
                            Category = "Other",
                            IsArchived = false,
                            Name = "Decline Bench Crunch"
                        },
                        new
                        {
                            Id = 162L,
                            Category = "Other",
                            IsArchived = false,
                            Name = "Kneeling Cable Crunch"
                        },
                        new
                        {
                            Id = 163L,
                            Category = "Other",
                            IsArchived = false,
                            Name = "Hanging Leg Raise"
                        },
                        new
                        {
                            Id = 164L,
                            Category = "Other",
                            IsArchived = false,
                            Name = "Hanging Knee Raise"
                        },
                        new
                        {
                            Id = 165L,
                            Category = "Other",
                            IsArchived = false,
                            Name = "Captain's Chair Leg Raise"
                        },
                        new
                        {
                            Id = 166L,
                            Category = "Other",
                            IsArchived = false,
                            Name = "Lying Leg Raise"
                        },
                        new
                        {
                            Id = 167L,
                            Category = "Other",
                            IsArchived = false,
                            Name = "Reverse Crunch"
                        },
                        new
                        {
                            Id = 168L,
                            Category = "Other",
                            IsArchived = false,
                            Name = "Plank"
                        },
                        new
                        {
                            Id = 169L,
                            Category = "Other",
                            IsArchived = false,
                            Name = "Cable Pallof Press"
                        },
                        new
                        {
                            Id = 170L,
                            Category = "Other",
                            IsArchived = false,
                            Name = "Russian Twist"
                        },
                        new
                        {
                            Id = 171L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Chest-Supported Wide-Grip Machine Row"
                        },
                        new
                        {
                            Id = 172L,
                            Category = "Pull",
                            IsArchived = false,
                            Name = "Chest-Supported Close-Grip Machine Row"
                        });
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.ExerciseMedia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExerciseId")
                        .HasColumnType("bigint");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("ExerciseMedia");
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.SessionExercise", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ExerciseId")
                        .HasColumnType("bigint");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int?>("PlannedSets")
                        .HasColumnType("integer");

                    b.Property<int>("RestSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(90);

                    b.Property<long>("WorkoutSessionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutSessionId", "ExerciseId")
                        .IsUnique();

                    b.ToTable("SessionExercises", t =>
                        {
                            t.HasCheckConstraint("CK_SessionExercise_PlannedSets_Positive", "\"PlannedSets\" IS NULL OR \"PlannedSets\" > 0");

                            t.HasCheckConstraint("CK_SessionExercise_RestSeconds_Range", "\"RestSeconds\" >= 0 AND \"RestSeconds\" <= 900");
                        });
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.SetEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExerciseId")
                        .HasColumnType("bigint");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<int?>("Rir")
                        .HasColumnType("integer");

                    b.Property<decimal>("Weight")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<long>("WorkoutSessionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutSessionId");

                    b.HasIndex("ExerciseId", "WorkoutSessionId");

                    b.ToTable("SetEntries", t =>
                        {
                            t.HasCheckConstraint("CK_SetEntry_Reps_Positive", "\"Reps\" > 0");

                            t.HasCheckConstraint("CK_SetEntry_Rir_NonNegative", "\"Rir\" IS NULL OR \"Rir\" >= 0");

                            t.HasCheckConstraint("CK_SetEntry_Weight_NonNegative", "\"Weight\" >= 0");
                        });
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.TemplateExercise", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ExerciseId")
                        .HasColumnType("bigint");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("PlannedSets")
                        .HasColumnType("integer");

                    b.Property<int>("RestSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(90);

                    b.Property<long>("WorkoutTemplateId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutTemplateId", "OrderIndex");

                    b.ToTable("TemplateExercises", t =>
                        {
                            t.HasCheckConstraint("CK_TemplateExercise_PlannedSets_Positive", "\"PlannedSets\" > 0");

                            t.HasCheckConstraint("CK_TemplateExercise_RestSeconds_Range", "\"RestSeconds\" >= 0 AND \"RestSeconds\" <= 900");
                        });
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("WeeklyTargetDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_User_WeeklyTargetDays_Range", "\"WeeklyTargetDays\" IS NULL OR (\"WeeklyTargetDays\" >= 1 AND \"WeeklyTargetDays\" <= 7)");
                        });
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.WorkoutSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Difficulty")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("TemplateId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.HasIndex("UserId", "StartedAt");

                    b.ToTable("WorkoutSessions", t =>
                        {
                            t.HasCheckConstraint("CK_WorkoutSession_EndedAt_After_StartedAt", "\"EndedAt\" IS NULL OR \"EndedAt\" > \"StartedAt\"");
                        });
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.WorkoutTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("WorkoutTemplates");
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.AiInsight", b =>
                {
                    b.HasOne("Grind.Api.Models.Entities.SetEntry", "SetEntry")
                        .WithMany("AiInsights")
                        .HasForeignKey("SetEntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Grind.Api.Models.Entities.User", "User")
                        .WithMany("AiInsights")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grind.Api.Models.Entities.WorkoutSession", "WorkoutSession")
                        .WithMany("AiInsights")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SetEntry");

                    b.Navigation("User");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.BodyWeightLog", b =>
                {
                    b.HasOne("Grind.Api.Models.Entities.User", "User")
                        .WithMany("BodyWeightLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.Exercise", b =>
                {
                    b.HasOne("Grind.Api.Models.Entities.User", "User")
                        .WithMany("Exercises")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.ExerciseMedia", b =>
                {
                    b.HasOne("Grind.Api.Models.Entities.Exercise", "Exercise")
                        .WithMany("Media")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.SessionExercise", b =>
                {
                    b.HasOne("Grind.Api.Models.Entities.Exercise", "Exercise")
                        .WithMany("SessionExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grind.Api.Models.Entities.WorkoutSession", "WorkoutSession")
                        .WithMany("SessionExercises")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.SetEntry", b =>
                {
                    b.HasOne("Grind.Api.Models.Entities.Exercise", "Exercise")
                        .WithMany("SetEntries")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grind.Api.Models.Entities.WorkoutSession", "WorkoutSession")
                        .WithMany("SetEntries")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.TemplateExercise", b =>
                {
                    b.HasOne("Grind.Api.Models.Entities.Exercise", "Exercise")
                        .WithMany("TemplateExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Grind.Api.Models.Entities.WorkoutTemplate", "WorkoutTemplate")
                        .WithMany("TemplateExercises")
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.WorkoutSession", b =>
                {
                    b.HasOne("Grind.Api.Models.Entities.WorkoutTemplate", "Template")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Grind.Api.Models.Entities.User", "User")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Template");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.WorkoutTemplate", b =>
                {
                    b.HasOne("Grind.Api.Models.Entities.User", "User")
                        .WithMany("WorkoutTemplates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.Exercise", b =>
                {
                    b.Navigation("Media");

                    b.Navigation("SessionExercises");

                    b.Navigation("SetEntries");

                    b.Navigation("TemplateExercises");
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.SetEntry", b =>
                {
                    b.Navigation("AiInsights");
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.User", b =>
                {
                    b.Navigation("AiInsights");

                    b.Navigation("BodyWeightLogs");

                    b.Navigation("Exercises");

                    b.Navigation("WorkoutSessions");

                    b.Navigation("WorkoutTemplates");
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.WorkoutSession", b =>
                {
                    b.Navigation("AiInsights");

                    b.Navigation("SessionExercises");

                    b.Navigation("SetEntries");
                });

            modelBuilder.Entity("Grind.Api.Models.Entities.WorkoutTemplate", b =>
                {
                    b.Navigation("TemplateExercises");

                    b.Navigation("WorkoutSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
